ARG WORDPRESS_VERSION=5.6.2
FROM wordpress:$WORDPRESS_VERSION
ARG WORDPRESS_VERSION

RUN echo "WORDPRESS_VERSION=$WORDPRESS_VERSION"

# install wordpress wp-client. It is rather useful
WORKDIR /tmp
RUN curl https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -O
RUN chmod +x wp-cli.phar
RUN mv wp-cli.phar /usr/local/bin/wp

# replace wp-content with our own
RUN rm -fr /usr/src/wordpress/wp-content
COPY wp-content/ /usr/src/wordpress/wp-content/
RUN chown -R www-data:www-data /usr/src/wordpress/wp-content


WORKDIR /var/www/html