apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  labels:
    app: cms
spec:
  type: LoadBalancer

---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress
spec:
  template:
    spec:
      containers:
        - name: wordpress
          env:
          - name: WORDPRESS_CONFIG_EXTRA
            value: >
              define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST'] . '/');
              define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST'] . '/');
              define('WP_MEMORY_LIMIT', getenv('WP_MEMORY_LIMIT'));
              define('WP_MAX_MEMORY_LIMIT', getenv('WP_MEMORY_LIMIT'));
          volumeMounts:
          - name: wordpress-uploads
            mountPath: /uploads
      volumes:
      - name: wordpress-uploads
        hostPath:
          path: '/Users/armindocachada/projects/wordpress-kustomize-skaffold-gitlab-ci-on-gke/data/uploads'
